---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # hack/tools/go.mod
  - package-ecosystem: gomod
    directory: "./hack/tools"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # test/fuzz/go.mod
  - package-ecosystem: gomod
    directory: "./test/fuzz"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # pkg/signature/kms/aws/go.mod
  - package-ecosystem: gomod
    directory: "./pkg/signature/kms/aws"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # pkg/signature/kms/azure/go.mod
  - package-ecosystem: gomod
    directory: "./pkg/signature/kms/azure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # pkg/signature/kms/gcp/go.mod
  - package-ecosystem: gomod
    directory: "./pkg/signature/kms/gcp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  # pkg/signature/kms/hashivault/go.mod
  - package-ecosystem: gomod
    directory: "./pkg/signature/kms/hashivault"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: "docker"
    directory: "/test/e2e"
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
        - "minor"
        - "patch"
