#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.16.8

jobs:
  e2e_test:
    name: e2e integration tests
    runs-on: ubuntu-latest
    services:
      vault:
        image: vault
        env:
          VAULT_DEV_ROOT_TOKEN_ID: testtoken
        ports:
        - 8200/tcp
      localstack:
        image: localstack/localstack:0.12.15
        ports:
        - 4566/tcp
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Pull chrome
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install chrome
      run: sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Docker Build
      working-directory: ./test/e2e
      run: docker-compose build

    - name: Unit Test
      run: go test -tags e2e -v ./test/e2e/...
    - name: Integeration test
      working-directory: ./test/e2e
      run: ./e2e-test.sh
