name: Cut Release

on:
  workflow_call:
    inputs:
      release_tag:
        required: false
        type: string
        description: 'Release tag. Will increment patch version if not specified.'
        default: ''
      key_ring:
        required: false
        type: string
        description: 'Key ring for cosign key'
      key_name:
        required: false
        type: string
        description: 'Key name for cosign key'
      workload_identity_provider:
        required: true
        type: string
        description: 'Workload idenitty provider to authenticate acceses.'
      service_account:
        required: true
        type: string
        description: 'Service account to run the release.'
      repo:
        required: true
        type: string
        description: 'The Sigstore repo to release.'


jobs:
  cut-release:
    name: Cut release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: 'projectsigstore'
      RELEASE_TAG: ${{ inputs.release_tag }}
    steps:
      - name: Check actor access
        if: ${{ !contains( fromJson('["bobcallaway","cpanato","dlorenc","lukehinds","priyawadhwa","vaikas","haydentherapper","znewman01"]'), github.actor ) }}
        run: exit 1

      - name: Checkout out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          path: ./src/github.com/sigstore/${{ inputs.repo }}

      - name: Set release tag if not specified
        if: ${{ inputs.release_tag == '' }}
        run: |
          git fetch --all --tags
          LATEST_DIGEST=`git rev-list --tags --max-count=1`
          LATEST_TAG=`git describe --tags ${LATEST_DIGEST}`
          NEW_VERSION=`echo "${TAG}" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g'`
          echo "RELEASE_TAG=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Start cloudbuild job
        working-directory: ./src/github.com/sigstore/${{ inputs.repo }}
        run: gcloud builds submit --no-source --async --config release/cloudbuild.yaml --substitutions _GIT_TAG=${{ env.RELEASE_TAG }},_TOOL_ORG=sigstore,_TOOL_REPO=${{ inputs.repo }},_STORAGE_LOCATION=${{ inputs.repo }}-releases,_KEY_RING=release-cosign,_KEY_NAME=cosign,_GITHUB_USER=sigstore-bot --project=${{ env.PROJECT_ID }}
